
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 03 03:24:31 CET 2021
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ASIGSUM = 10;
  public static final int CORCHOP = 30;
  public static final int CONST = 12;
  public static final int TWOPOINTS = 27;
  public static final int CASE = 11;
  public static final int INT = 14;
  public static final int LESS = 4;
  public static final int LLAVECL = 34;
  public static final int NOT = 7;
  public static final int AND = 6;
  public static final int LLAVEOP = 33;
  public static final int TYPE = 24;
  public static final int COMMA = 32;
  public static final int SEMICOL = 26;
  public static final int NUM = 37;
  public static final int PLUS = 2;
  public static final int MAIN = 20;
  public static final int IF = 22;
  public static final int ID = 36;
  public static final int PRINTINT = 16;
  public static final int EOF = 0;
  public static final int ASIG = 9;
  public static final int RETURN = 21;
  public static final int error = 1;
  public static final int BREAK = 13;
  public static final int VOID = 25;
  public static final int EQ = 5;
  public static final int SWITCH = 17;
  public static final int ELSE = 23;
  public static final int WHILE = 18;
  public static final int DEFAULT = 19;
  public static final int PROD = 3;
  public static final int STRING = 35;
  public static final int AUTOINC = 8;
  public static final int PARENCL = 29;
  public static final int PARENOP = 28;
  public static final int PRINT = 15;
  public static final int CORCHCL = 31;
}

